---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://jamisondance.com

posts:
  permalink: /:year/:i_month/:i_day/:title
  summary_lines: 10
  latest: 10

pages:
  permalink: 'pretty'
