title : Interpreted Dance
tagline: Blog Tagline
author :
  name : Jamison Dance
  email : jergason@gmail.com
  github : jergason
  twitter : jergason

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
